//
//  CommentModels.swift
//  CleanPosts
//
//  Created by Francisca Velueta on 08/12/19.
//  Copyright (c) 2019 Francis Velueta. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CommentScene {
  // MARK: Use cases
  
  enum Load {
    struct Request {
    }
    struct Response {
        let coments : [Comment]
    }
    struct ViewModel {
         let coments : [Comment]
    }
  }
}
