//
//  PostRouter.swift
//  CleanPosts
//
//  Created by Francisca Velueta on 07/12/19.
//  Copyright (c) 2019 Francis Velueta. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PostRoutingLogic {
  func routeToSComments()
}

protocol PostDataPassing {
  var dataStore: PostDataStore? { get }
}

class PostRouter: NSObject, PostRoutingLogic, PostDataPassing {
  weak var viewController: PostViewController?
  var dataStore: PostDataStore?
  
  // MARK: Routing
  
  func routeToSComments()
  {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(identifier: "commentsPost") as! CommentViewController
    
    var destinationDS = destinationVC.router!.dataStore!
    passDataToComments(source: dataStore!, destination: &destinationDS)
    navigateToComments(source: viewController!, destination: destinationVC)
    
  }

  // MARK: Navigation
  
  func navigateToComments(source: PostViewController, destination: CommentViewController) {
    source.show(destination, sender: nil)
  }
  
//   MARK: Passing data
  
  func passDataToComments(source: PostDataStore, destination: inout CommentDataStore) {
    destination.postId = source.postId
  }
}
